version: '3.4'

x-wp-core-volume:
  &wp_core
  type: bind
  source: ./wp
  target: /var/www/html

x-php-ini:
  &php_ini
  type: bind
  source: ./config/php.conf.ini
  target: /usr/local/etc/php/conf.d/conf.ini

x-startup-commands:
  &commands
  type: bind
  source: ./commands
  target: /usr/local/bin/commands

networks:
  default:
    driver: bridge

volumes:
  db_data:

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - ${IP}:12306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    healthcheck:
      test: "/usr/bin/mysqladmin --password=${DB_ROOT_PASSWORD}"
      timeout: 5s
      retries: 20
    networks:
      - default
  wpcore:
    image: wordpress:php8.0-fpm
    ports:
      - ${IP}:12080:80
    working_dir: /var/www/html
    volumes:
      - *php_ini
      - *wp_core
      - *commands
    command: [ "/bin/sh" ,"-c", "/usr/local/bin/commands/init-wp.sh" ]
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DB_PORT: "${DB_PORT}"
      WORDPRESS_DEBUG: 1
    depends_on:
      - mariadb
    networks:
      - default

  wpcli:
    image: wordpress:cli
    tty: true
    volumes:
      - *php_ini
      - *wp_core
      - *commands
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DB_PORT: "${DB_PORT}"
      WORDPRESS_DEBUG: 1
    depends_on:
      - mariadb
      - wpcore
    networks:
      - default

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:12088:80
    networks:
      - default
